apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:m6Qb/vlMtFG4S+Lta1Pku9vNByvHONOU,iv:kC4cZ7kZxhxtweytvywmLx1Q8VIBUVC3iOXNUwr4t/s=,tag:JaWlCu0U6qmgPSUWNDRLmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncngusd5skmca24ll4u4459wu4wqxh8sw2kh0prg59deeu073avsa6h7k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bTd6L0RPKzN6L1J6WXBF
            Y1RwU0FzZDZSVHdEMTRZNXpWeFE2UCtOMlRBCithZTJ2anJlTHV5RnNFSGVUdjNX
            NzdhcDlyYlBydjI3dEtUNEs2MUl6MHMKLS0tIDdheGNacWdydkM3RnVKOE95QkNl
            OHRxeFJyb0l6QStxUmJ4YnZmb3J4QWcKRGPKRalPqRnxetsfswgNzZq/zyUm9u5R
            Wci18SjoVYJbLRlfQa7mcOLuP/MoqaG4qOpbZF04Mich9aHUpgQhpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T17:04:57Z"
    mac: ENC[AES256_GCM,data:/8F6/grga51+19T8KZj/Wiq/oJEBxNHAq87mbRrryUcYz7Osscxm/NVMmIf2yeNoUbQZogGmXOfxcq7AkIwbMjMVio7+DznbOe07n5Ju/PT0jSE/ByCot/hHdSi9e5siLmw/JmDJD6uqIN1y7WZVuftCqWcMQV9DbcwEHtxqYh0=,iv:mEM6bQBkc4TMn5OziVlcQaMQljhLY9OD9NfGkfVudS8=,tag:I9xgPLRgSkk05G08Dh96fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
