apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:paCGGFQW4vMSc4hV7uuABwHU6kn1DPmZACQRO+795x9SJF9cG2Mlag==,iv:rYvi4TkBJ7gWqWAlYI649wd5hwgP5K5ICVVBt2WWWTo=,tag:gafOLXVBBeNTjAXvTcqJXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncngusd5skmca24ll4u4459wu4wqxh8sw2kh0prg59deeu073avsa6h7k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUTVqc3cybEFJeUwvcldm
            U04rZTQ0Y25KRFk1NGU3eTI1Y0pRRUhrTmxzCmJEZk9leFNaZ0xSQlNrbjJxOHI3
            aUsxYmhYMjlxQ29uU2ZWR2txSlk2Mm8KLS0tIElyaTBha29TSEdKbjFKaDZUQzR5
            SDJVdElwTk1qRmhIcEY5bm9ZT0Z6RmcKmTiFs+cCG3mxrn23zyCeIvT31D3EtrKY
            /BDHoHWbGM4FOSgwLNeNsLNFibtyWXhjSBe4YyjTVzY15YcY7YVbTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T21:44:12Z"
    mac: ENC[AES256_GCM,data:0tBy0l6lN11hA0VBvnycZshqj580ivXvOnbSe0eh32npf7vRS6gaIyKUiAE+RyufhfghJeXzJSeCfZ0khHq0P6V9zb3LeQPd5vVIoTSsqBFJpDncfnEzBPuxkqQ5FMaugKef4a0e9xeiq8fQAPDF/xG2cjRTaYtOMGk/YEjqgMA=,iv:02mdXoe0OLqIwz0ekQrTjxJu6OM7BrNTdkFPkK5EU5I=,tag:HFoa0De52f+HLtCrFHHqdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
