apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:x9R+XXB7b09HFRWGRmvQtAs2qrCZPQCwwFq0+qkf5cm2hsFKWZKDIA==,iv:Dw15/CAT9qWl9dklRpgNlhU7d3Q9YvO9yQlYHGX+cN4=,tag:lj+KMtRXUQt8TZiXyrXuJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncngusd5skmca24ll4u4459wu4wqxh8sw2kh0prg59deeu073avsa6h7k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmhZRmNMeUhXUUZJTnBI
            MERlYmlveWY4aFh5VmlraE5qZ2ZtZm81VkVVCmxEbTYwdjgxdkRic2txb2pPZjJ2
            cFR4U3haV01xaGFEcUpZWkpMc0RpUmsKLS0tIGVWWkxKZStXKzU0M0FWSzI1TnR5
            cE1WanYrTVhZWnBlZkl4NlNXb3ltcEUKsvqP2eGoLIZLIMoeB/U3CIZDU4HjgWvx
            k5Cj+/kj9rA6H8kp29cDTDM0ppgU0Sn+rkUMkx6LIPUqzEkJL6Rceg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T03:35:37Z"
    mac: ENC[AES256_GCM,data:Qj76nm634TCXDZvfN8GN+k0kVWDOv+i1txiKXf99CYlFktotSwoh+65XnGCHSMpeeT3bRrpfWP5xqg/eFTpKj2c0jyAEURrgQt/BdmGnEjUrE8LeqMqTxfs6yY0DTpgm24tvk798NVyhSIPlg4lmq0Dltxz1VOGxXu17+nF3/hw=,iv:gIV+ptlYJCZYvLkVgt2JwACiWrGALiL1JTqXy2zfPcg=,tag:JTDYzBfbvST6RakzElq4JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
