apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:2RMVdRtb3SZQ6mDY,iv:JE5vgxYLc/PIcI6BDIQKLH9oA8zxIkRer1ReJ5/dG78=,tag:FV3aNizJ2A5b0jAV0Y3e8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncngusd5skmca24ll4u4459wu4wqxh8sw2kh0prg59deeu073avsa6h7k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y2VjQjFoNC85UmRZTkhn
            NnY3OGgrYUFMNTRYaWQzZXJNbkg5OGtiNFNZClpUSHF1UTc2bXJJS0ZOQ1NZYml6
            SVFtSFdubG1BQTNLWFZ2UC9Ndi9sdHMKLS0tIEtCTXZXZHFYWEw2QkZOT1IyeEVl
            TVpZWUpGbC9ZWXdNMHlYeE1ad0VmdzAKQVxruZahmhIinaBggr2mcu6DRPRLx2Xl
            PE7HaeqtUtGVZ4izpK6MTyKniKbc7xV5Y/St1fwvow665FX+C2+skQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T17:04:58Z"
    mac: ENC[AES256_GCM,data:p4uWZMOWzIsXO2e1bqox6aZ7Y3dhPCiSSmsjgGl+Ynsjdq2QF7pxH4vC5+SZRvhu+2j3T0d6CqWBkYLbKSnt9PDoMQMAYAYptU+cogutJHWO9foVbEYN1YigIj8KzkirS6iXqjZlf3j/sQGG13v9y7rcjhRd3vRCwqWxy7RcUpQ=,iv:Mz8R8MGG3vyEfb7c3gKu3q5bxrD8cdOlYzPchyhlnEc=,tag:E1FF+dzIo2emzs4iYgvEaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
